# Generated by Django 6.0.4 on 2026-04-15 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicTerm',
            fields=[
                ('term_id', models.AutoField(db_column='TermID', primary_key=True, serialize=False)),
                ('semester', models.CharField(db_column='Semester', max_length=20)),
                ('academic_year', models.CharField(db_column='AcademicYear', max_length=20)),
                ('start_date', models.DateField(db_column='StartDate')),
                ('end_date', models.DateField(db_column='EndDate')),
                ('add_drop_deadline', models.DateField(db_column='AddDropDeadline')),
                ('is_current', models.BooleanField(db_column='IsCurrent', default=False)),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
            ],
            options={
                'db_table': 'AcademicTerm',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(db_column='CourseID', primary_key=True, serialize=False)),
                ('course_code', models.CharField(db_column='CourseCode', max_length=50, unique=True)),
                ('course_name', models.CharField(db_column='CourseName', max_length=255)),
                ('credits', models.IntegerField(db_column='Credits')),
                ('department_id', models.IntegerField(db_column='DepartmentID')),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('average_grade', models.DecimalField(db_column='AverageGrade', decimal_places=2, default=0, max_digits=5)),
                ('success_rate', models.DecimalField(db_column='SuccessRate', decimal_places=2, default=0, max_digits=5)),
                ('is_deleted', models.BooleanField(db_column='IsDeleted', default=False)),
            ],
            options={
                'db_table': 'Course',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.AutoField(db_column='DeptID', primary_key=True, serialize=False)),
                ('dept_name', models.CharField(db_column='DeptName', max_length=255, unique=True)),
                ('dept_code', models.CharField(db_column='DeptCode', max_length=50, unique=True)),
                ('head_teacher_id', models.IntegerField(blank=True, db_column='HeadTeacherID', null=True)),
                ('budget', models.DecimalField(db_column='Budget', decimal_places=2, default=0, max_digits=12)),
                ('budget_used', models.DecimalField(db_column='BudgetUsed', decimal_places=2, default=0, max_digits=12)),
                ('location', models.CharField(blank=True, db_column='Location', max_length=255, null=True)),
                ('max_student_capacity', models.IntegerField(db_column='MaxStudentCapacity', default=500)),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('is_deleted', models.BooleanField(db_column='IsDeleted', default=False)),
            ],
            options={
                'db_table': 'Department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('enrollment_id', models.AutoField(db_column='EnrollmentID', primary_key=True, serialize=False)),
                ('student_id', models.IntegerField(db_column='StudentID')),
                ('section_id', models.IntegerField(db_column='SectionID')),
                ('status', models.CharField(db_column='Status', default='Enrolled', max_length=50)),
                ('numeric_grade', models.DecimalField(blank=True, db_column='NumericGrade', decimal_places=2, max_digits=4, null=True)),
                ('letter_grade', models.CharField(blank=True, db_column='LetterGrade', max_length=2, null=True)),
                ('grade_points', models.DecimalField(blank=True, db_column='GradePoints', decimal_places=2, max_digits=3, null=True)),
                ('grade_locked', models.BooleanField(db_column='GradeLocked', default=False)),
            ],
            options={
                'db_table': 'Enrollment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_id', models.AutoField(db_column='SectionID', primary_key=True, serialize=False)),
                ('section_code', models.CharField(db_column='SectionCode', max_length=50, unique=True)),
                ('section_name', models.CharField(db_column='SectionName', max_length=255)),
                ('term_id', models.IntegerField(db_column='TermID')),
                ('course_id', models.IntegerField(db_column='CourseID')),
                ('teacher_id', models.IntegerField(blank=True, db_column='TeacherID', null=True)),
                ('room_id', models.IntegerField(blank=True, db_column='RoomID', null=True)),
                ('schedule', models.CharField(blank=True, db_column='Schedule', max_length=100, null=True)),
                ('max_capacity', models.IntegerField(db_column='MaxCapacity', default=40)),
                ('current_enrollment', models.IntegerField(db_column='CurrentEnrollment', default=0)),
                ('status', models.CharField(db_column='Status', default='Active', max_length=50)),
            ],
            options={
                'db_table': 'Section',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(db_column='StudentID', primary_key=True, serialize=False)),
                ('student_number', models.CharField(db_column='StudentNumber', max_length=50, unique=True)),
                ('first_name', models.CharField(db_column='FirstName', max_length=100)),
                ('last_name', models.CharField(db_column='LastName', max_length=100)),
                ('email', models.CharField(db_column='Email', max_length=255, unique=True)),
                ('department_id', models.IntegerField(blank=True, db_column='DepartmentID', null=True)),
                ('cumulative_gpa', models.DecimalField(db_column='CumulativeGPA', decimal_places=2, default=0, max_digits=3)),
                ('semester_gpa', models.DecimalField(db_column='SemesterGPA', decimal_places=2, default=0, max_digits=3)),
                ('total_credits_earned', models.IntegerField(db_column='TotalCreditsEarned', default=0)),
                ('status', models.CharField(db_column='Status', default='Active', max_length=50)),
                ('academic_standing', models.CharField(db_column='AcademicStanding', default='Good Standing', max_length=50)),
                ('attendance_percentage', models.DecimalField(db_column='AttendancePercentage', decimal_places=2, default=100, max_digits=5)),
                ('has_outstanding_fees', models.BooleanField(db_column='HasOutstandingFees', default=False)),
                ('performance_flag', models.CharField(db_column='PerformanceFlag', default='Normal', max_length=50)),
                ('is_deleted', models.BooleanField(db_column='IsDeleted', default=False)),
            ],
            options={
                'db_table': 'Student',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.AutoField(db_column='TeacherID', primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_column='FirstName', max_length=100)),
                ('last_name', models.CharField(db_column='LastName', max_length=100)),
                ('email', models.CharField(db_column='Email', max_length=255, unique=True)),
                ('department_id', models.IntegerField(blank=True, db_column='DepartmentID', null=True)),
                ('status', models.CharField(db_column='Status', default='Active', max_length=50)),
                ('average_teaching_rating', models.DecimalField(db_column='AverageTeachingRating', decimal_places=2, default=0, max_digits=3)),
                ('is_deleted', models.BooleanField(db_column='IsDeleted', default=False)),
            ],
            options={
                'db_table': 'Teacher',
                'managed': False,
            },
        ),
    ]
