# Generated by Django 6.0.4 on 2026-04-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('assessment_id', models.AutoField(db_column='AssessmentID', primary_key=True, serialize=False)),
                ('section_id', models.IntegerField(db_column='SectionID')),
                ('assessment_type', models.CharField(db_column='AssessmentType', max_length=50)),
                ('assessment_name', models.CharField(db_column='AssessmentName', max_length=255)),
                ('max_score', models.DecimalField(db_column='MaxScore', decimal_places=2, max_digits=5)),
                ('weight', models.DecimalField(db_column='Weight', decimal_places=2, max_digits=5)),
                ('due_date', models.DateField(blank=True, db_column='DueDate', null=True)),
            ],
            options={
                'db_table': 'Assessment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_id', models.AutoField(db_column='AttendanceID', primary_key=True, serialize=False)),
                ('student_id', models.IntegerField(db_column='StudentID')),
                ('section_id', models.IntegerField(db_column='SectionID')),
                ('date', models.DateField(db_column='Date')),
                ('status', models.CharField(db_column='Status', max_length=20)),
                ('remarks', models.TextField(blank=True, db_column='Remarks', null=True)),
            ],
            options={
                'db_table': 'Attendance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('log_id', models.AutoField(db_column='LogID', primary_key=True, serialize=False)),
                ('table_name', models.CharField(db_column='TableName', max_length=100)),
                ('record_id', models.IntegerField(db_column='RecordID')),
                ('action', models.CharField(db_column='Action', max_length=50)),
                ('old_value', models.TextField(blank=True, db_column='OldValue', null=True)),
                ('new_value', models.TextField(blank=True, db_column='NewValue', null=True)),
                ('trigger_name', models.CharField(db_column='TriggerName', max_length=100)),
                ('changed_by', models.CharField(db_column='ChangedBy', default='SYSTEM', max_length=100)),
                ('changed_at', models.DateTimeField(db_column='ChangedAt')),
                ('ip_address', models.CharField(blank=True, db_column='IPAddress', max_length=50, null=True)),
                ('session_id', models.CharField(blank=True, db_column='SessionID', max_length=100, null=True)),
                ('checksum', models.CharField(blank=True, db_column='Checksum', max_length=255, null=True)),
            ],
            options={
                'db_table': 'AuditLog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('room_id', models.AutoField(db_column='RoomID', primary_key=True, serialize=False)),
                ('room_number', models.CharField(db_column='RoomNumber', max_length=50, unique=True)),
                ('building', models.CharField(db_column='Building', max_length=100)),
                ('capacity', models.IntegerField(db_column='Capacity')),
                ('current_occupancy', models.IntegerField(db_column='CurrentOccupancy', default=0)),
                ('utilization_rate', models.DecimalField(db_column='UtilizationRate', decimal_places=2, default=0, max_digits=5)),
                ('type', models.CharField(db_column='Type', max_length=50)),
            ],
            options={
                'db_table': 'Classroom',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('fee_id', models.AutoField(db_column='FeeID', primary_key=True, serialize=False)),
                ('student_id', models.IntegerField(db_column='StudentID')),
                ('term_id', models.IntegerField(blank=True, db_column='TermID', null=True)),
                ('fee_type', models.CharField(db_column='FeeType', max_length=50)),
                ('amount', models.DecimalField(db_column='Amount', decimal_places=2, max_digits=10)),
                ('paid_amount', models.DecimalField(db_column='PaidAmount', decimal_places=2, default=0, max_digits=10)),
                ('due_date', models.DateField(db_column='DueDate')),
                ('paid_date', models.DateField(blank=True, db_column='PaidDate', null=True)),
                ('status', models.CharField(db_column='Status', default='Pending', max_length=50)),
                ('payment_method', models.CharField(blank=True, db_column='PaymentMethod', max_length=50, null=True)),
                ('late_fee', models.DecimalField(db_column='LateFee', decimal_places=2, default=0, max_digits=8)),
                ('created_date', models.DateField(blank=True, db_column='CreatedDate', null=True)),
                ('created_by', models.CharField(db_column='CreatedBy', default='SYSTEM', max_length=100)),
            ],
            options={
                'db_table': 'Fee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('scholarship_id', models.AutoField(db_column='ScholarshipID', primary_key=True, serialize=False)),
                ('student_id', models.IntegerField(db_column='StudentID')),
                ('term_id', models.IntegerField(blank=True, db_column='TermID', null=True)),
                ('scholarship_name', models.CharField(db_column='ScholarshipName', max_length=255)),
                ('amount', models.DecimalField(db_column='Amount', decimal_places=2, max_digits=10)),
                ('start_date', models.DateField(blank=True, db_column='StartDate', null=True)),
                ('end_date', models.DateField(blank=True, db_column='EndDate', null=True)),
                ('award_date', models.DateField(blank=True, db_column='AwardDate', null=True)),
                ('renewal_date', models.DateField(blank=True, db_column='RenewalDate', null=True)),
                ('eligibility_status', models.CharField(db_column='EligibilityStatus', default='Active', max_length=50)),
            ],
            options={
                'db_table': 'Scholarship',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentAssessment',
            fields=[
                ('student_assessment_id', models.AutoField(db_column='StudentAssessmentID', primary_key=True, serialize=False)),
                ('enrollment_id', models.IntegerField(db_column='EnrollmentID')),
                ('assessment_id', models.IntegerField(db_column='AssessmentID')),
                ('score', models.DecimalField(blank=True, db_column='Score', decimal_places=2, max_digits=5, null=True)),
                ('date_recorded', models.DateField(blank=True, db_column='DateRecorded', null=True)),
            ],
            options={
                'db_table': 'StudentAssessment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SystemMode',
            fields=[
                ('mode_id', models.IntegerField(db_column='ModeID', primary_key=True, serialize=False)),
                ('environment', models.CharField(db_column='Environment', default='PRODUCTION', max_length=50)),
                ('strict_mode', models.BooleanField(db_column='StrictMode', default=True)),
                ('allow_test_data', models.BooleanField(db_column='AllowTestData', default=False)),
                ('debug_logging', models.BooleanField(db_column='DebugLogging', default=False)),
                ('last_changed', models.DateTimeField(blank=True, db_column='LastChanged', null=True)),
            ],
            options={
                'db_table': 'SystemMode',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('setting_key', models.CharField(db_column='SettingKey', max_length=100, primary_key=True, serialize=False)),
                ('setting_value', models.TextField(db_column='SettingValue')),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('category', models.CharField(blank=True, db_column='Category', max_length=100, null=True)),
                ('last_modified', models.DateTimeField(blank=True, db_column='LastModified', null=True)),
                ('modified_by', models.CharField(db_column='ModifiedBy', default='SYSTEM', max_length=100)),
            ],
            options={
                'db_table': 'SystemSettings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('waitlist_id', models.AutoField(db_column='WaitlistID', primary_key=True, serialize=False)),
                ('student_id', models.IntegerField(db_column='StudentID')),
                ('section_id', models.IntegerField(db_column='SectionID')),
                ('position', models.IntegerField(db_column='Position')),
                ('requested_at', models.DateTimeField(db_column='RequestedAt')),
                ('notified_at', models.DateTimeField(blank=True, db_column='NotifiedAt', null=True)),
                ('status', models.CharField(db_column='Status', default='Waiting', max_length=50)),
                ('offered_until', models.DateTimeField(blank=True, db_column='OfferedUntil', null=True)),
            ],
            options={
                'db_table': 'Waitlist',
                'managed': False,
            },
        ),
    ]
